import React from 'react';
import { Link } from 'react-router-dom';
import LegalLayout from '../../components/LegalLayout';
import { CONTACT_EMAIL, MIN_AGE, LEGAL_LAST_UPDATED } from '../../lib/legal';

export default function PrivacyPolicy() {
  return (
    <LegalLayout title="Privacy Policy" lastUpdated={LEGAL_LAST_UPDATED}>
      <p>
        PitchNest (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) operates the PitchNest platform — a web and mobile
        application that helps startup founders practice pitches with AI-generated investor personas. This Privacy Policy
        explains how we collect, use, store, and delete your information.
      </p>

      <h2>1. Information we collect</h2>
      <ul>
        <li><strong>Account data:</strong> name, email address, and password (stored as a secure hash).</li>
        <li><strong>Profile data:</strong> startup name, industry, and goals you provide during onboarding.</li>
        <li><strong>Pitch content:</strong> uploaded pitch decks (PDF), session transcripts, AI evaluation reports, and optional video or audio recordings from pitch sessions.</li>
        <li><strong>Device permissions:</strong> if you use camera and microphone features, audio/video is processed for live pitch sessions. We request permissions only when needed for a pitch.</li>
        <li><strong>Usage data:</strong> basic logs such as session timestamps, scores, and technical error logs to keep the service running.</li>
      </ul>

      <h2>2. How we use your information</h2>
      <ul>
        <li>Provide and improve the PitchNest service (authentication, deck storage, live AI pitch rooms, analytics).</li>
        <li>Process your pitch content through AI models to generate feedback, scores, and transcripts.</li>
        <li>Respond to support requests and legal obligations.</li>
        <li>Send service-related communications (e.g., password reset) when applicable.</li>
      </ul>

      <h2>3. AI processing disclosure</h2>
      <p>
        PitchNest uses <strong>Google Gemini</strong> and related AI services to power live conversations and post-pitch
        evaluations. Your voice, text, camera feed, slide content, and deck text may be sent to Google&apos;s APIs for
        processing. AI responses are <strong>generated by artificial intelligence</strong> — they do not represent real
        venture capitalists, financial advice, or investment offers.
      </p>
      <p>
        Do not share confidential information you are not comfortable sending to a third-party AI provider. Review{' '}
        <a href="https://ai.google.dev/gemini-api/terms" target="_blank" rel="noopener noreferrer">
          Google&apos;s Gemini API terms
        </a>{' '}
        for details on their data handling.
      </p>

      <h2>4. Third-party services</h2>
      <ul>
        <li><strong>Supabase</strong> — database and file storage (accounts, decks, session data, media).</li>
        <li><strong>Google Gemini</strong> — AI inference for live pitch and evaluation.</li>
        <li><strong>Hosting providers</strong> — e.g., Render (backend), Vercel (frontend), as configured for deployment.</li>
      </ul>
      <p>These providers process data on our behalf under their own privacy policies and security practices.</p>

      <h2>5. Data retention</h2>
      <p>
        We retain your data while your account is active. When you delete your account, we delete your profile, pitch
        sessions, decks, and associated media from our systems within a reasonable period (typically within 30 days).
        Backups may take additional time to purge. We may retain minimal records where required by law (e.g., fraud
        prevention or tax compliance).
      </p>

      <h2>6. Your rights and choices</h2>
      <ul>
        <li><strong>Access &amp; correction:</strong> update profile information in Settings.</li>
        <li><strong>Delete account:</strong> use Settings → Account → Delete Account, or visit our{' '}
          <Link to="/delete-account">Delete Account</Link> page (works in a browser without reinstalling the app).</li>
        <li><strong>Permissions:</strong> revoke camera/microphone access in your device settings at any time.</li>
      </ul>
      <p>
        Depending on your location (e.g., EU/UK, California), you may have additional rights to access, port, or restrict
        processing of your data. Contact us at{' '}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      </p>

      <h2>7. Children</h2>
      <p>
        PitchNest is not directed at children under {MIN_AGE}. We do not knowingly collect
        data from anyone under {MIN_AGE}. Contact us if you believe a child has provided personal data.
      </p>

      <h2>8. Cookies and local storage</h2>
      <p>
        PitchNest uses browser local storage to keep you signed in (session token and profile). We do not use third-party
        advertising cookies. Essential service data is stored locally only for authentication convenience; delete your
        account or sign out to clear it from your device.
      </p>

      <h2>9. Content and age</h2>
      <p>
        PitchNest is rated for users age {MIN_AGE} and older. The app contains business-education content and AI-simulated
        investor dialogue. It does not include violence, profanity, or mature themes. AI personas may ask challenging
        business questions but remain professional in tone.
      </p>

      <h2>10. Security</h2>
      <p>
        We use industry-standard measures including HTTPS, hashed passwords, and authenticated API access. No method of
        transmission or storage is 100% secure.
      </p>

      <h2>11. International transfers</h2>
      <p>
        Your data may be processed in the United States and other countries where our service providers operate. By using
        PitchNest, you consent to such transfers subject to applicable law.
      </p>

      <h2>12. Changes</h2>
      <p>
        We may update this policy. We will post the revised version with an updated &quot;Last updated&quot; date. Continued
        use after changes constitutes acceptance.
      </p>

      <h2>13. Contact &amp; related policies</h2>
      <p>
        PitchNest<br />
        Email: <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>
      </p>
      <p>
        See also:{' '}
        <Link to="/terms">Terms of Service</Link>,{' '}
        <Link to="/delete-account">Delete Account</Link>,{' '}
        <Link to="/support">Support</Link>.
      </p>
    </LegalLayout>
  );
}
